#include<stdio.h>
#include<string.h>
#include<math.h>
int main()
{
    int i,j,k,l,a,d,N,h;
    int A=26,B=27,C=28,D=29,E=30,F=31,G=32,H=33,I=34,J=35,K=36,L=37,M=38,Nn=39,O=40,P=41,Q=42,R=43,S=44,T=45,U=46,V=47,W=48,X=49,Y=50,Z=51;
    scanf("%d",&N);
    char check[60]="ABCDEFGHIJKLMNOPQRSTUVWXYZABCDEFGHIJKLMNOPQRSTUVWXYZ",str[100],r_str[100];
    for(i=0; i<N; i++){
        scanf("%s",str);
        scanf("%d",&a);
        d=strlen(str);
        for(k=0,j=0; j<d; j++){
            if(str[j]=='A'){
                r_str[k]=check[A-a];
                k++;
            }
            if(str[j]=='B'){
                r_str[k]=check[B-a];
                k++;
            }
            if(str[j]=='C'){
                r_str[k]=check[C-a];
                k++;
            }
            if(str[j]=='D'){
                r_str[k]=check[D-a];
                k++;
            }
            if(str[j]=='E'){
                r_str[k]=check[E-a];
                k++;
            }
            if(str[j]=='F'){
                r_str[k]=check[F-a];
                k++;
            }
            if(str[j]=='G'){
                r_str[k]=check[G-a];
                k++;
            }
            if(str[j]=='H'){
                r_str[k]=check[H-a];
                k++;
            }
            if(str[j]=='I'){
                r_str[k]=check[I-a];
                k++;
            }
            if(str[j]=='J'){
                r_str[k]=check[J-a];
                k++;
            }
            if(str[j]=='K'){
                r_str[k]=check[K-a];
                k++;
            }
            if(str[j]=='L'){
                r_str[k]=check[L-a];
                k++;
            }
            if(str[j]=='M'){
                r_str[k]=check[M-a];
                k++;
            }
            if(str[j]=='N'){
                r_str[k]=check[Nn-a];
                k++;
            }
            if(str[j]=='O'){
                r_str[k]=check[O-a];
                k++;
            }
            if(str[j]=='P'){
                r_str[k]=check[P-a];
                k++;
            }
            if(str[j]=='Q'){
                r_str[k]=check[Q-a];
                k++;
            }
            if(str[j]=='R'){
                r_str[k]=check[R-a];
                k++;
            }
            if(str[j]=='S'){
                r_str[k]=check[S-a];
                k++;
            }
            if(str[j]=='T'){
                r_str[k]=check[T-a];
                k++;
            }
            if(str[j]=='U'){
                r_str[k]=check[U-a];
                k++;
            }
            if(str[j]=='V'){
                r_str[k]=check[V-a];
                k++;
            }
            if(str[j]=='W'){
                r_str[k]=check[W-a];
                k++;
            }
            if(str[j]=='X'){
                r_str[k]=check[X-a];
                k++;
            }
            if(str[j]=='Y'){
                r_str[k]=check[Y-a];
                k++;
            }
            if(str[j]=='Z'){
                r_str[k]=check[Z-a];
                k++;
            }
        }
        r_str[k]='\0';
        printf("%s\n",r_str);
    }
}
